import type { MumblePreset } from "./types";

export const defaultPresets: MumblePreset[] = [
  {
    id: "cute-npc",
    name: "Cute NPC",
    swatch: "#f472b6",
    params: {
      basicFreq: 330,
      wordCountMultiplier: 1.05,
      syllableLengthMs: 92,
      syllableLengthRandomness: 0.28,
      pitchRandomSemitone: 4.8,
      pitchFallAtEnd: true,
      speedCurve: 0.18,
      timingJitterMs: 18,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.08,
      filterFreq: 1350,
      filterQ: 4.6,
      attackMs: 7,
      releaseMs: 42,
      volumeDb: 4,
      seed: 1234,
    },
  },
  {
    id: "robot-guard",
    name: "Robot Guard",
    swatch: "#22c55e",
    params: {
      basicFreq: 145,
      wordCountMultiplier: 0.85,
      syllableLengthMs: 78,
      syllableLengthRandomness: 0.08,
      pitchRandomSemitone: 1.4,
      pitchFallAtEnd: false,
      speedCurve: 0.42,
      timingJitterMs: 4,
      ringModFreq: 48,
      ringModDepth: 0.56,
      noiseAmount: 0.04,
      filterFreq: 920,
      filterQ: 9.5,
      attackMs: 4,
      releaseMs: 28,
      volumeDb: 3,
      seed: 2201,
    },
  },
  {
    id: "tiny-creature",
    name: "Tiny Creature",
    swatch: "#38bdf8",
    params: {
      basicFreq: 640,
      wordCountMultiplier: 1.35,
      syllableLengthMs: 56,
      syllableLengthRandomness: 0.34,
      pitchRandomSemitone: 9.2,
      pitchFallAtEnd: true,
      speedCurve: 0.62,
      timingJitterMs: 22,
      ringModFreq: 12,
      ringModDepth: 0.14,
      noiseAmount: 0.03,
      filterFreq: 2450,
      filterQ: 6.2,
      attackMs: 3,
      releaseMs: 28,
      volumeDb: 2,
      seed: 8128,
    },
  },
  {
    id: "tired-villager",
    name: "Tired Villager",
    swatch: "#f59e0b",
    params: {
      basicFreq: 190,
      wordCountMultiplier: 0.78,
      syllableLengthMs: 138,
      syllableLengthRandomness: 0.36,
      pitchRandomSemitone: 3.2,
      pitchFallAtEnd: true,
      speedCurve: -0.54,
      timingJitterMs: 30,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.14,
      filterFreq: 780,
      filterQ: 3.1,
      attackMs: 16,
      releaseMs: 82,
      volumeDb: 4,
      seed: 5633,
    },
  },
  {
    id: "monster",
    name: "Monster",
    swatch: "#ef4444",
    params: {
      basicFreq: 82,
      wordCountMultiplier: 0.7,
      syllableLengthMs: 122,
      syllableLengthRandomness: 0.24,
      pitchRandomSemitone: 6.4,
      pitchFallAtEnd: true,
      speedCurve: -0.08,
      timingJitterMs: 24,
      ringModFreq: 28,
      ringModDepth: 0.32,
      noiseAmount: 0.3,
      filterFreq: 520,
      filterQ: 5.8,
      attackMs: 9,
      releaseMs: 96,
      volumeDb: 2,
      seed: 9090,
    },
  },
];
