import type { MumblePreset } from "./types";

export const defaultPresets: MumblePreset[] = [
  {
    id: "cute-npc",
    name: "Cute NPC",
    swatch: "#f472b6",
    params: {
      basicFreq: 330,
      wordCountMultiplier: 1.05,
      syllableLengthMs: 92,
      syllableLengthRandomness: 0.28,
      pitchRandomSemitone: 4.8,
      pitchFallAtEnd: true,
      speedCurve: 0.18,
      timingJitterMs: 18,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.08,
      filterFreq: 1350,
      filterQ: 4.6,
      attackMs: 7,
      releaseMs: 42,
      volumeDb: 4,
      seed: 1234,
    },
  },
  {
    id: "robot-guard",
    name: "Robot Guard",
    swatch: "#22c55e",
    params: {
      basicFreq: 145,
      wordCountMultiplier: 0.85,
      syllableLengthMs: 78,
      syllableLengthRandomness: 0.08,
      pitchRandomSemitone: 1.4,
      pitchFallAtEnd: false,
      speedCurve: 0.42,
      timingJitterMs: 4,
      ringModFreq: 48,
      ringModDepth: 0.56,
      noiseAmount: 0.04,
      filterFreq: 920,
      filterQ: 9.5,
      attackMs: 4,
      releaseMs: 28,
      volumeDb: 3,
      seed: 2201,
    },
  },
  {
    id: "soft-mascot",
    name: "Soft Mascot",
    swatch: "#fb7185",
    params: {
      basicFreq: 390,
      wordCountMultiplier: 1.18,
      syllableLengthMs: 86,
      syllableLengthRandomness: 0.2,
      pitchRandomSemitone: 4.2,
      pitchFallAtEnd: true,
      speedCurve: 0.24,
      timingJitterMs: 10,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.035,
      filterFreq: 1420,
      filterQ: 3.1,
      attackMs: 12,
      releaseMs: 58,
      volumeDb: 2,
      seed: 4412,
    },
  },
  {
    id: "talkative-merchant",
    name: "Talkative Merchant",
    swatch: "#eab308",
    params: {
      basicFreq: 250,
      wordCountMultiplier: 1.22,
      syllableLengthMs: 76,
      syllableLengthRandomness: 0.18,
      pitchRandomSemitone: 3.6,
      pitchFallAtEnd: true,
      speedCurve: 0.34,
      timingJitterMs: 14,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.08,
      filterFreq: 1180,
      filterQ: 3.6,
      attackMs: 8,
      releaseMs: 44,
      volumeDb: 3,
      seed: 7341,
    },
  },
  {
    id: "tiny-creature",
    name: "Tiny Creature",
    swatch: "#38bdf8",
    params: {
      basicFreq: 520,
      wordCountMultiplier: 1.22,
      syllableLengthMs: 66,
      syllableLengthRandomness: 0.24,
      pitchRandomSemitone: 5.8,
      pitchFallAtEnd: true,
      speedCurve: 0.46,
      timingJitterMs: 12,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.018,
      filterFreq: 1780,
      filterQ: 3.2,
      attackMs: 8,
      releaseMs: 46,
      volumeDb: 0.5,
      seed: 8128,
    },
  },
  {
    id: "forest-spirit",
    name: "Forest Spirit",
    swatch: "#14b8a6",
    params: {
      basicFreq: 320,
      wordCountMultiplier: 0.95,
      syllableLengthMs: 128,
      syllableLengthRandomness: 0.16,
      pitchRandomSemitone: 3.8,
      pitchFallAtEnd: true,
      speedCurve: -0.18,
      timingJitterMs: 10,
      ringModFreq: 10,
      ringModDepth: 0.06,
      noiseAmount: 0.08,
      filterFreq: 1280,
      filterQ: 2.8,
      attackMs: 28,
      releaseMs: 135,
      volumeDb: 1,
      seed: 6874,
    },
  },
  {
    id: "tired-villager",
    name: "Tired Villager",
    swatch: "#f59e0b",
    params: {
      basicFreq: 190,
      wordCountMultiplier: 0.78,
      syllableLengthMs: 138,
      syllableLengthRandomness: 0.36,
      pitchRandomSemitone: 3.2,
      pitchFallAtEnd: true,
      speedCurve: -0.54,
      timingJitterMs: 30,
      ringModFreq: 0,
      ringModDepth: 0,
      noiseAmount: 0.14,
      filterFreq: 780,
      filterQ: 3.1,
      attackMs: 16,
      releaseMs: 82,
      volumeDb: 4,
      seed: 5633,
    },
  },
  {
    id: "monster",
    name: "Monster",
    swatch: "#ef4444",
    params: {
      basicFreq: 82,
      wordCountMultiplier: 0.7,
      syllableLengthMs: 122,
      syllableLengthRandomness: 0.24,
      pitchRandomSemitone: 6.4,
      pitchFallAtEnd: true,
      speedCurve: -0.08,
      timingJitterMs: 24,
      ringModFreq: 28,
      ringModDepth: 0.32,
      noiseAmount: 0.3,
      filterFreq: 520,
      filterQ: 5.8,
      attackMs: 9,
      releaseMs: 96,
      volumeDb: 2,
      seed: 9090,
    },
  },
  {
    id: "deep-boss",
    name: "Deep Boss",
    swatch: "#7c3aed",
    params: {
      basicFreq: 68,
      wordCountMultiplier: 0.62,
      syllableLengthMs: 150,
      syllableLengthRandomness: 0.16,
      pitchRandomSemitone: 3.8,
      pitchFallAtEnd: true,
      speedCurve: -0.22,
      timingJitterMs: 12,
      ringModFreq: 22,
      ringModDepth: 0.22,
      noiseAmount: 0.22,
      filterFreq: 430,
      filterQ: 4.8,
      attackMs: 18,
      releaseMs: 135,
      volumeDb: 1,
      seed: 9907,
    },
  },
];
