import type {
  EmotionId,
  ExpressionDefinition,
  ExpressionModifiers,
  ExpressionSettings,
  SpeakingStyleId,
} from "./types";

export const EXPRESSION_VERSION = "0.3.0";

export const defaultExpressionSettings: ExpressionSettings = {
  emotion: "neutral",
  style: "normal",
  intensity: 65,
};

export const neutralExpressionSettings: ExpressionSettings = {
  emotion: "neutral",
  style: "normal",
  intensity: 0,
};

export const identityExpressionModifiers: ExpressionModifiers = {
  pitchShiftSemitone: 0,
  durationMultiplier: 1,
  timingJitterMultiplier: 1,
  pitchRandomMultiplier: 1,
  gainDb: 0,
  noiseMultiplier: 1,
  attackMultiplier: 1,
  releaseMultiplier: 1,
  pauseScale: 1,
  endingPitchSemitone: 0,
  emphasisChanceBonus: 0,
  brightnessMultiplier: 1,
};

export const emotionDefinitions: ExpressionDefinition<EmotionId>[] = [
  {
    id: "neutral",
    name: "Neutral",
    description: "Default delivery",
    modifiers: {},
  },
  {
    id: "happy",
    name: "Happy",
    description: "Higher, quicker, brighter",
    modifiers: {
      pitchShiftSemitone: 2.2,
      durationMultiplier: 0.88,
      timingJitterMultiplier: 0.85,
      pitchRandomMultiplier: 1.15,
      gainDb: 1,
      noiseMultiplier: 0.9,
      attackMultiplier: 0.85,
      releaseMultiplier: 0.86,
      pauseScale: 0.82,
      endingPitchSemitone: 1.2,
      emphasisChanceBonus: 0.05,
      brightnessMultiplier: 1.12,
    },
  },
  {
    id: "angry",
    name: "Angry",
    description: "Short, loud, hard-edged",
    modifiers: {
      pitchShiftSemitone: -0.6,
      durationMultiplier: 0.78,
      timingJitterMultiplier: 0.8,
      pitchRandomMultiplier: 0.95,
      gainDb: 2.4,
      noiseMultiplier: 1.35,
      attackMultiplier: 0.55,
      releaseMultiplier: 0.62,
      pauseScale: 0.75,
      endingPitchSemitone: -0.3,
      emphasisChanceBonus: 0.16,
      brightnessMultiplier: 1.18,
    },
  },
  {
    id: "sad",
    name: "Sad",
    description: "Lower, slower, softer",
    modifiers: {
      pitchShiftSemitone: -2.4,
      durationMultiplier: 1.22,
      timingJitterMultiplier: 0.9,
      pitchRandomMultiplier: 0.72,
      gainDb: -2,
      noiseMultiplier: 0.9,
      attackMultiplier: 1.25,
      releaseMultiplier: 1.35,
      pauseScale: 1.35,
      endingPitchSemitone: -1.8,
      emphasisChanceBonus: -0.08,
      brightnessMultiplier: 0.82,
    },
  },
  {
    id: "nervous",
    name: "Nervous",
    description: "Fast and unstable",
    modifiers: {
      pitchShiftSemitone: 1.1,
      durationMultiplier: 0.86,
      timingJitterMultiplier: 1.75,
      pitchRandomMultiplier: 1.75,
      gainDb: -0.4,
      noiseMultiplier: 1.12,
      attackMultiplier: 0.75,
      releaseMultiplier: 0.8,
      pauseScale: 0.9,
      endingPitchSemitone: 0.8,
      emphasisChanceBonus: 0.08,
      brightnessMultiplier: 1.04,
    },
  },
  {
    id: "sleepy",
    name: "Sleepy",
    description: "Slow, soft, low",
    modifiers: {
      pitchShiftSemitone: -3,
      durationMultiplier: 1.42,
      timingJitterMultiplier: 0.65,
      pitchRandomMultiplier: 0.58,
      gainDb: -2.6,
      noiseMultiplier: 0.82,
      attackMultiplier: 1.7,
      releaseMultiplier: 1.65,
      pauseScale: 1.5,
      endingPitchSemitone: -2.2,
      emphasisChanceBonus: -0.12,
      brightnessMultiplier: 0.76,
    },
  },
  {
    id: "surprised",
    name: "Surprised",
    description: "High, short, sudden",
    modifiers: {
      pitchShiftSemitone: 4,
      durationMultiplier: 0.72,
      timingJitterMultiplier: 1.1,
      pitchRandomMultiplier: 1.25,
      gainDb: 1.5,
      noiseMultiplier: 1.05,
      attackMultiplier: 0.55,
      releaseMultiplier: 0.75,
      pauseScale: 0.7,
      endingPitchSemitone: 2.5,
      emphasisChanceBonus: 0.18,
      brightnessMultiplier: 1.2,
    },
  },
  {
    id: "scared",
    name: "Scared",
    description: "High, shaky, lighter",
    modifiers: {
      pitchShiftSemitone: 2.5,
      durationMultiplier: 0.88,
      timingJitterMultiplier: 1.95,
      pitchRandomMultiplier: 1.9,
      gainDb: -0.8,
      noiseMultiplier: 1.2,
      attackMultiplier: 0.65,
      releaseMultiplier: 0.95,
      pauseScale: 1.1,
      endingPitchSemitone: 1.8,
      emphasisChanceBonus: 0.11,
      brightnessMultiplier: 1.08,
    },
  },
];

export const speakingStyleDefinitions: ExpressionDefinition<SpeakingStyleId>[] = [
  {
    id: "normal",
    name: "Normal",
    description: "Unmodified style",
    modifiers: {},
  },
  {
    id: "whisper",
    name: "Whisper",
    description: "Soft and noisy",
    modifiers: {
      pitchShiftSemitone: 0.5,
      durationMultiplier: 1.04,
      timingJitterMultiplier: 1.05,
      pitchRandomMultiplier: 0.9,
      gainDb: -5.5,
      noiseMultiplier: 1.9,
      attackMultiplier: 1.25,
      releaseMultiplier: 1.25,
      pauseScale: 1.15,
      endingPitchSemitone: 0.2,
      emphasisChanceBonus: -0.06,
      brightnessMultiplier: 0.75,
    },
  },
  {
    id: "shout",
    name: "Shout",
    description: "Loud and clipped",
    modifiers: {
      pitchShiftSemitone: 1,
      durationMultiplier: 0.78,
      timingJitterMultiplier: 0.8,
      pitchRandomMultiplier: 0.85,
      gainDb: 4.5,
      noiseMultiplier: 1.25,
      attackMultiplier: 0.45,
      releaseMultiplier: 0.72,
      pauseScale: 0.75,
      endingPitchSemitone: 0.4,
      emphasisChanceBonus: 0.14,
      brightnessMultiplier: 1.2,
    },
  },
  {
    id: "mutter",
    name: "Mutter",
    description: "Low and swallowed",
    modifiers: {
      pitchShiftSemitone: -1.4,
      durationMultiplier: 0.92,
      timingJitterMultiplier: 1.35,
      pitchRandomMultiplier: 0.75,
      gainDb: -2.5,
      noiseMultiplier: 1.25,
      attackMultiplier: 1.05,
      releaseMultiplier: 1.1,
      pauseScale: 0.9,
      endingPitchSemitone: -0.8,
      emphasisChanceBonus: -0.1,
      brightnessMultiplier: 0.72,
    },
  },
  {
    id: "formal",
    name: "Formal",
    description: "Measured and even",
    modifiers: {
      pitchShiftSemitone: -0.2,
      durationMultiplier: 1.08,
      timingJitterMultiplier: 0.55,
      pitchRandomMultiplier: 0.55,
      gainDb: -0.2,
      noiseMultiplier: 0.75,
      attackMultiplier: 1.05,
      releaseMultiplier: 1,
      pauseScale: 1.18,
      endingPitchSemitone: -0.4,
      emphasisChanceBonus: -0.05,
      brightnessMultiplier: 1.02,
    },
  },
  {
    id: "chant",
    name: "Chant",
    description: "Regular and sustained",
    modifiers: {
      pitchShiftSemitone: 0,
      durationMultiplier: 1.24,
      timingJitterMultiplier: 0.32,
      pitchRandomMultiplier: 0.35,
      gainDb: 0.6,
      noiseMultiplier: 0.7,
      attackMultiplier: 1.2,
      releaseMultiplier: 1.4,
      pauseScale: 1.05,
      endingPitchSemitone: 0.2,
      emphasisChanceBonus: 0.04,
      brightnessMultiplier: 0.95,
    },
  },
];
